services:
  fastapi:
    image: python:3.13
    container_name: url_shorter_fastapi
    build:
      context: urlShorter
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - service_nerwork

  db:
    image: postgres:15
    container_name: url_shorter_postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./urlShorter/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - service_nerwork

  nginx:
    image: nginx:latest
    container_name: url_shorter_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
    networks:
      - service_nerwork

volumes:
  postgres_data:

networks:
  service_nerwork:
