"""empty message

Revision ID: f1f7375f043d
Revises: 
Create Date: 2025-06-03 12:48:25.953065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f7375f043d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorted_urls',
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('created_by_ip', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('alias_len', sa.Integer(), nullable=False),
    sa.Column('available_after', sa.Boolean(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index('idx_alias_len_and_alias', 'shorted_urls', ['alias_len', 'alias'], unique=False)
    op.create_index('idx_alias_len_desc_and_alias_desc', 'shorted_urls', [sa.literal_column('alias_len DESC'), sa.literal_column('alias DESC')], unique=False)
    op.create_index(op.f('ix_shorted_urls_alias_len'), 'shorted_urls', ['alias_len'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shorted_urls_alias_len'), table_name='shorted_urls')
    op.drop_index('idx_alias_len_desc_and_alias_desc', table_name='shorted_urls')
    op.drop_index('idx_alias_len_and_alias', table_name='shorted_urls')
    op.drop_table('shorted_urls')
    # ### end Alembic commands ###
